/*Anti cheats that don't require include in all scripts*/
#include <AFkill> //Anti fake kill -Rogue
#include <AntiFC>//Anti fake clients - Rogue
#include <rAgc>//Anti gun cheats -Rogue
#include <rAsc>//Anti speed cheats- Rogue
#include <rVM>//Anti illegal car mods -Emmet_
#include <rAcs>//Anti car spam - Rogue
#include <rED> //Anti dialog spoof/crash- Emmet_ (easyDialog)

/*Includes that provide spam/bug protection (not worth a ban)*/
#include <AntiSpam>//Anti chat spam- Rogue
#include <AntiSba>//Anti slide bug abuse- Rogue
#include <Flaggers>//Lag spike\desnyc detector- Rogue

/*Anti cheats that do require include in all scripts and only edit through GM*/
#include <AntiJC>//Anti jetpack cheats- Rogue
#include <Opba>//Anti airbreak\teleport - Rogue
#include <rAct>//Anti car trolls - Rogue
#include <rEac>//Anti carswing\particlespam - Lorenc_
#include <rAmc>//Anti money cheats- Rogue
