// generated by "sampctl package generate"

#include "a_samp.inc"
#include "Rogue-AC.inc"

#tryinclude "zcmd.inc"

main() {
	CreateVehicle(561, 0.0, 0.0, 0.0, 0.0, 0, 0, 0);
}

public OnPlayerFakeKill(playerid, spoofedid, spoofedreason, faketype)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d just spoof killed ID %d reason %d type %d", playerid, spoofedid, spoofedreason, faketype);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerFakeConnect(playerid)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is fake connecting!", playerid);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerJetpackCheat(playerid)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is using jetpack cheats!", playerid);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerGodmode(playerid, gmtype)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is using godmode cheats type %d!", playerid, gmtype);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerSpamChat(playerid)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is spamming chat!", playerid);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerGunCheat(playerid, weaponid, ammo, hacktype)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d just used weapon cheats weapon %d ammo %d type %d!", playerid, weaponid, ammo, hacktype);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerSpeedCheat(playerid, speedtype)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d just speed cheats type %d!", playerid, speedtype);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerBreakAir(playerid, breaktype)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d used airbreak/teleport cheats type %d !", playerid, breaktype);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerSpamCars(playerid, number)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d used car spammed %d vehicles !", playerid, number);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerCarTroll(playerid, vehicleid, trolledid, trolltype)
{
	new Test_String[80];
	if(trolledid == INVALID_PLAYER_ID)
		format(Test_String, sizeof(Test_String), "ID %d used car troll cheats vehicle %d type %d !", playerid, vehicleid, trolltype);
	else
		format(Test_String, sizeof(Test_String), "ID %d used car troll cheats on ID %d vehicle %d type %d !", playerid, trolledid, vehicleid, trolltype); 
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerCashCheat(playerid, oldcash, newcash, amount)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d used money cheats for %d !", playerid, amount);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerCarSwing(playerid, vehicleid)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d used car swing cheats vehicle %d !", playerid, vehicleid);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerParticleSpam(playerid, vehicleid)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d used car particle spam cheats vehicle %d !", playerid, vehicleid);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnVehicleModEx(playerid, vehicleid, componentid, illegal)
{
	new Test_String[80];
	if(illegal)
	{
		format(Test_String, sizeof(Test_String), "ID %d used car mod cheats component %d vehicle %d !", playerid, componentid, vehicleid);
		SendClientMessageToAll(-1, Test_String);
		print(Test_String);
	}
	return 1;
}

public OnPlayerSlide(playerid, weaponid, Float:speed)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is slide bugging weapon %d !", playerid, weaponid);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerLagout(playerid, lagtype, ping)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is lagging type %d ping %d !", playerid, lagtype, ping);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

public OnPlayerBugAttempt(playerid, bugcode)
{
	new Test_String[80];
	format(Test_String, sizeof(Test_String), "ID %d is using bug cheats type %d!", playerid, bugcode);
	SendClientMessageToAll(-1, Test_String);
	print(Test_String);
	return 1;
}

/* Easy dialog by Emmet_ Example:*/
#if defined CMD
CMD:weapons(playerid, params[])
{
	Dialog_Show(playerid, WeaponMenu, DIALOG_STYLE_LIST, "Weapon Menu", "9mm\nSilenced 9mm\nDesert Eagle\nShotgun\nSawn-off Shotgun\nCombat Shotgun", "Select", "Cancel");
	return 1;
}
#endif

Dialog:WeaponMenu(playerid, response, listitem, inputtext[])
{
	if (response)
	{
		new str[64];
		format(str, 64, "You have selected the '%s'.", inputtext);

		GivePlayerWeapon(playerid, listitem + 22, 500);
		SendClientMessage(playerid, -1, str);
	}
	return 1;
}

public OnDialogPerformed(playerid, dialog[], response, success)
{
	if (!strcmp(dialog, "WeaponMenu") && IsPlayerInAnyVehicle(playerid))
	{
		SendClientMessage(playerid, -1, "You must be on-foot to spawn a weapon.");
		return 0;
	}
	return 1;
}
/* Easy dialog by Emmet_ Example ^ */

//OnPlayerViolate default example:
#define MAX_WARNS_AC 3 //Max warns before kick in severe case 1
static s_playerWarnings[MAX_PLAYERS];
forward OnPlayerViolate(playerid, severity, violationCode, const violationName[]);
public OnPlayerViolate(playerid, severity, violationCode, const violationName[])
{
	new acString[STRING_SIZE_LARGE], name[MAX_PLAYER_NAME];
	GetPlayerName(playerid, name, sizeof name);
	
	switch(severity)
	{
		case SEVERITY_CASE_ONE:
		{
			if(s_playerWarnings[playerid] < MAX_WARNS_AC) s_playerWarnings[playerid]++;
			else 
			{
				format(acString, sizeof acString, "Player %s was kicked after 3 warnings, reason: Code violation #%d", name, violationCode);
				Kick(playerid);
				SendClientMessageToAll(AC_MESSAGE_COLOR, acString);

			}
		}
		case SEVERITY_CASE_TWO:
		{
			format(acString, sizeof acString, "Player %s was kicked, reason: Code violation #%d", name, violationCode);
			Kick(playerid);
			SendClientMessageToAll(AC_MESSAGE_COLOR, acString);
		}
		case SEVERITY_CASE_THREE:
		{
			format(acString, sizeof acString, "Player %s was banned, reason: Code violation #%d", name, violationCode);
			BanEx(playerid, violationName);
			SendClientMessageToAll(AC_MESSAGE_COLOR, acString);
		}
	}
	return 1;
}
public OnPlayerDisconnect(playerid, reason)
{
	s_playerWarnings[playerid] = 0;
	return 1;
}
